apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursey-python
  labels:
    app: coursey-python
spec:
  replicas: {{ .Values.python.replicaCount }}
  selector:
    matchLabels:
      app: coursey-python
  template:
    metadata:
      labels:
        app: coursey-python
    spec:
      containers:
      - name: python-app
        image: "{{ .Values.python.image.repository }}:{{ .Values.python.image.tag }}"
        imagePullPolicy: Always 
        ports:
        - containerPort: {{ .Values.python.service.port }}
          name: python-http
        
        readinessProbe:
          tcpSocket:
            port: {{ .Values.python.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: {{ .Values.python.service.port }}
          initialDelaySeconds: 20
          periodSeconds: 10